AppVersion: dev.1.0.0


Kafka:
  BoostrapServer: ""

HTTP:
  Port: ":8888"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Redis:
  RedisAddr: "localhost:6379"
  RedisPassword:
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  DB: 0

Postgresql:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDBName: service_promotion
  PostgresqlSslMode: "disable"
